version: '3.7'
services:
  web:
    image: hitalos/laravel:latest
    ports:
    - "80:80"
    volumes:
    - ./:/var/www
    links:
    - "db"
    environment:
      DB_HOST: "db"
      DB_DATABASE: "laravel"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      DB_CONNECTION: "mysql"
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql/
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
